"""Add schedule fields to Medicine model

Revision ID: 50218166fbbf
Revises: 66e1eedb67cd
Create Date: 2025-10-04 00:06:31.113447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50218166fbbf'
down_revision = '66e1eedb67cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('times', sa.Text(), nullable=True))
        batch_op.alter_column('schedule_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'daily'"))
        batch_op.drop_column('times_json')
        batch_op.drop_column('days_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('times_json', sa.TEXT(), nullable=True))
        batch_op.alter_column('schedule_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'daily'"))
        batch_op.drop_column('times')
        batch_op.drop_column('days')

    # ### end Alembic commands ###
